version: "2"
services:
  item-app:
    image: dwinabela/item-app:v1

    # melakukan port mapping ke port 80
    ports:
      - "8080:80"
    depends_on:
      - item-db

  item-db:
    # menggunakan docker mongo:3 dari docker hub
    image: mongo:3

    # memakai volume bernama app-db dengan target /data/db di container
    volumes:
      - app-db:/data/db

# memiliki satu buah volume bernama app-db
volumes:
  app-db: